apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-delete-ceph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block-delete
