apiVersion: v1
kind: ConfigMap
metadata:
  name: locketapi-configmap
data:
  Issuer: https://yourauthserver.com
  Audience: OnionAPI
  TokenLifespan: "60"
  AUTH_MECHANISM: "SCRAM-SHA-256"
  MONGO_HOST: "103.82.134.110:30011,103.82.134.110:30012,103.82.134.110:30013"
  PRIMARY_MONGO_NAME: mongodb_primary
  MONGO_DATABASE: Locket