apiVersion:  apps/v1
kind: Deployment
metadata:
  name: locketapi
  labels:
    app: locketapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locketapi
  template:
    metadata:
      labels:
        app: locketapi
    spec:
      containers:
      - name: locketapi
        image: onionsm/locketapi:4.7.1
        ports:
        - containerPort: 8081
        env: 
        - name: DatabaseName
          valueFrom:
            configMapKeyRef:
              name: locketapi-configmap
              key: MONGO_DATABASE
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: locketapi-secret
              key: MONGODB_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: locketapi-secret
              key: MONGODB_PASSWORD
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: locketapi-configmap
              key: MONGO_DATABASE
        - name: PRIMARY_MONGO_NAME
          valueFrom:
            configMapKeyRef:
              name: locketapi-configmap
              key: PRIMARY_MONGO_NAME
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: locketapi-configmap
              key: MONGO_HOST

        - name: AUTH_MECHANISM
          valueFrom:
            configMapKeyRef:
              name: locketapi-configmap
              key: AUTH_MECHANISM    

        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: locketapi-secret
              key: JWT_SECRET_KEY

        - name: Issuer
          valueFrom:
            configMapKeyRef:
              name: locketapi-configmap
              key: Issuer
        - name: Audience
          valueFrom:
            configMapKeyRef:
              name: locketapi-configmap
              key: Audience
        - name: TokenLifespan
          valueFrom:
            configMapKeyRef:
              name: locketapi-configmap
              key: TokenLifespan
          
