apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'server-monitor'
        metrics_path: /node-exporter-grafana/metrics
        static_configs:
          - targets: ['k8s-loadbalancer.xn--hanh-0na.vn']
      - job_name: 'database-monitor'
        metrics_path: /node-exporter-database/metrics
        static_configs:
          - targets: ['k8s-loadbalancer.xn--hanh-0na.vn']
      - job_name: 'node-exporter-worker11'
        metrics_path: /node-exporter-cluster1-worker11/metrics
        static_configs:
          - targets: ['k8s-loadbalancer.xn--hanh-0na.vn']
      - job_name: 'node-exporter-worker12'
        metrics_path: /node-exporter-cluster1-worker12/metrics
        static_configs:
          - targets: ['k8s-loadbalancer.xn--hanh-0na.vn']
