apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-delete
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Gi