apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service
  MONGO_PORT: "27017"
  MONGO_HOST: 172.18.0.4
  DatabaseName: Locket
  MONGO_DATABASE: Locket
  PRIMARY_MONGO_NAME: mongodb_primary
  AUTH_MECHANISM: "SCRAM-SHA-256"