apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cluster1
spec:
  ingressClassName: nginx
  rules:
  - host: 103.82.37.167
    http:
      paths:
      - path: /node-exporter-service
        pathType: Prefix
        backend:
          service:
            name: node-exporter-service
            port:
              number: 9100
